server:
  host: localhost
  port: 8080

grpc:
  host: localhost
  port: 50059

upstreams:
  auth: localhost:50051
  customer: localhost:50052
  kyc: localhost:50053
  document: localhost:50054
  account: localhost:50055
  ledger: localhost:50056
  antifraud: localhost:50057
  notification: localhost:50058

jwks_url: http://localhost:8081/.well-known/jwks.json
jwks_refresh_interval: 5m # рез сколько клиент берет ключи у jwks сервера

request_timeout: 30s