// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Danila Kuryakin",
            "url": "https://github.com/danila-kuryakin/banking_mini_cores"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Возвращает данные пользователя и пару токенов. Access-токен передаётся дальше в заголовке Authorization.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Вход по email и паролю",
                "parameters": [
                    {
                        "description": "Email и пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Пользователь и пара токенов",
                        "schema": {
                            "$ref": "#/definitions/dto.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Тело запроса не прошло валидацию",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Неверные учётные данные",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка auth-service",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "description": "Отзывает refresh-токен. Ранее выданный access-токен продолжает действовать до истечения срока.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Выход из сессии",
                "parameters": [
                    {
                        "description": "Refresh-токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.LogoutRequest"
                        }
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Сессия завершена, тело ответа пустое"
                    },
                    "400": {
                        "description": "Тело запроса не прошло валидацию или токен неизвестен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка auth-service",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/officers": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Заводит учётную запись с ролью officer. Доступно только роли admin.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Создание сотрудника",
                "parameters": [
                    {
                        "description": "Email и пароль сотрудника",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.CreateOfficerRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Сотрудник создан",
                        "schema": {
                            "$ref": "#/definitions/dto.User"
                        }
                    },
                    "400": {
                        "description": "Тело запроса не прошло валидацию",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Роль не admin",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка auth-service",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/refresh": {
            "post": {
                "description": "Выдаёт новую пару токенов по refresh-токену. Старый refresh-токен после обмена недействителен.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Обновление пары токенов",
                "parameters": [
                    {
                        "description": "Refresh-токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RefreshRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Новая пара токенов",
                        "schema": {
                            "$ref": "#/definitions/dto.TokenPair"
                        }
                    },
                    "400": {
                        "description": "Тело запроса не прошло валидацию",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Refresh-токен просрочен или отозван",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка auth-service",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Создаёт учётную запись клиента. Пароль — от 8 до 72 символов.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Регистрация пользователя",
                "parameters": [
                    {
                        "description": "Email и пароль",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Пользователь создан",
                        "schema": {
                            "$ref": "#/definitions/dto.RegisterResponse"
                        }
                    },
                    "400": {
                        "description": "Тело запроса не прошло валидацию",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Email уже зарегистрирован",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка auth-service",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/validate": {
            "post": {
                "description": "Служебный метод: сообщает, валиден ли токен, и возвращает идентификатор владельца, роль и срок действия.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Проверка access-токена",
                "parameters": [
                    {
                        "description": "Access-токен",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.ValidateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Результат проверки; valid=false для просроченного токена",
                        "schema": {
                            "$ref": "#/definitions/dto.ValidateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Тело запроса не прошло валидацию",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Ошибка auth-service",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Постраничный список клиентов, отсортированный по дате создания по убыванию. Доступно ролям officer и admin.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "Список клиентов",
                "parameters": [
                    {
                        "maximum": 100,
                        "minimum": 0,
                        "type": "integer",
                        "description": "Размер страницы, по умолчанию 20",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Сколько записей пропустить",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Страница списка",
                        "schema": {
                            "$ref": "#/definitions/dto.ListCustomers"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Роль не officer и не admin",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer/{user_id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает клиента вместе с профилем и текущим статусом. Клиент видит только себя, officer и admin - любого.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "Карточка клиента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Клиент найден",
                        "schema": {
                            "$ref": "#/definitions/dto.Customer"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Профиль принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Клиент не найден",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Записывает анкетные данные. Поле birth_date передаётся строкой в формате YYYY-MM-DD и может быть пустым. Когда профиль заполнен целиком, клиент переходит в статус profile_filled и дальнейшее редактирование запрещается.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "Обновление профиля клиента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Поля профиля",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.UpdateProfile"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Профиль обновлён",
                        "schema": {
                            "$ref": "#/definitions/dto.Customer"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса или профиль больше не редактируется",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Профиль принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Клиент не найден",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer/{user_id}/files": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Постраничный список файлов, отсортированный по дате создания по убыванию. Незавершённые загрузки тоже видны - у них status = uploaded.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Список файлов клиента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "maximum": 100,
                        "minimum": 0,
                        "type": "integer",
                        "description": "Размер страницы, по умолчанию 20",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "minimum": 0,
                        "type": "integer",
                        "description": "Сколько записей пропустить",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Страница списка",
                        "schema": {
                            "$ref": "#/definitions/dto.ListFiles"
                        }
                    },
                    "400": {
                        "description": "Некорректные параметры запроса",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Файлы принадлежат другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Заводит запись о файле и возвращает presigned-ссылку. Файл клиент кладёт сам: PUT по upload_url с телом файла, gateway байты не принимает. После заливки нужно вызвать confirm. Типы: passport, selfie, proof_of_address.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Заявка на загрузку файла",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Тип файла и исходное имя",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/dto.InitUpload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ссылка на загрузку",
                        "schema": {
                            "$ref": "#/definitions/dto.UploadTicket"
                        }
                    },
                    "400": {
                        "description": "Некорректное тело запроса или неизвестный тип файла",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Файлы принадлежат другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer/{user_id}/files/required": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Загружены ли подтверждённые файлы обязательных типов (паспорт и селфи). В missing перечислено недостающее.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Комплектность файлов",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Состояние комплекта",
                        "schema": {
                            "$ref": "#/definitions/dto.RequiredFiles"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Файлы принадлежат другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer/{user_id}/files/{file_id}/confirm": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Проверяет залитый файл: размер не больше 10 МБ, тип определяется по содержимому (jpeg, png, pdf), считается sha256. Только после этого файл становится доступен для скачивания. Повторный вызов по подтверждённому файлу ничего не меняет.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Подтверждение загрузки",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID файла из ответа на заявку",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Файл подтверждён",
                        "schema": {
                            "$ref": "#/definitions/dto.File"
                        }
                    },
                    "400": {
                        "description": "Файл пустой, больше 10 МБ или неподдерживаемого типа",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Файл принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Файл не найден",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Файл этого типа уже подтверждён",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer/{user_id}/files/{file_id}/url": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает presigned-ссылку со сроком жизни 5 минут. Скачивает по ней клиент сам, gateway файл не отдаёт. Работает только для подтверждённых файлов.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "files"
                ],
                "summary": "Ссылка на скачивание",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "UUID файла",
                        "name": "file_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Ссылка на скачивание",
                        "schema": {
                            "$ref": "#/definitions/dto.DownloadTicket"
                        }
                    },
                    "400": {
                        "description": "Файл ещё не подтверждён",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Файл принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Файл не найден",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/customer/{user_id}/status": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Возвращает текущий статус и момент его последней смены. Возможные значения: new, profile_filled, on_kyc, active, rejected, blocked.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "customer"
                ],
                "summary": "Статус клиента",
                "parameters": [
                    {
                        "type": "string",
                        "description": "UUID пользователя или me - текущий пользователь",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Текущий статус",
                        "schema": {
                            "$ref": "#/definitions/dto.CustomerStatus"
                        }
                    },
                    "401": {
                        "description": "Отсутствует или недействителен access-токен",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Профиль принадлежит другому пользователю",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Клиент не найден",
                        "schema": {
                            "$ref": "#/definitions/dto.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.CreateOfficerRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "dto.Customer": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "profile": {
                    "$ref": "#/definitions/dto.Profile"
                },
                "status": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.CustomerStatus": {
            "type": "object",
            "properties": {
                "changed_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "dto.DownloadTicket": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        },
        "dto.ErrorResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "dto.File": {
            "type": "object",
            "properties": {
                "confirmed_at": {
                    "type": "string"
                },
                "content_type": {
                    "type": "string",
                    "example": "image/png"
                },
                "created_at": {
                    "type": "string"
                },
                "filename": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "sha256": {
                    "type": "string"
                },
                "size_bytes": {
                    "type": "integer"
                },
                "status": {
                    "type": "string",
                    "example": "confirmed"
                },
                "type": {
                    "type": "string",
                    "example": "passport"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.InitUpload": {
            "type": "object",
            "properties": {
                "filename": {
                    "type": "string",
                    "example": "passport.png"
                },
                "type": {
                    "type": "string",
                    "enum": [
                        "passport",
                        "selfie",
                        "proof_of_address"
                    ],
                    "example": "passport"
                }
            }
        },
        "dto.ListCustomers": {
            "type": "object",
            "properties": {
                "customers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.Customer"
                    }
                }
            }
        },
        "dto.ListFiles": {
            "type": "object",
            "properties": {
                "files": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.File"
                    }
                }
            }
        },
        "dto.LoginRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "dto.LoginResponse": {
            "type": "object",
            "properties": {
                "tokens": {
                    "$ref": "#/definitions/dto.TokenPair"
                },
                "user": {
                    "$ref": "#/definitions/dto.User"
                }
            }
        },
        "dto.LogoutRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.Profile": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "citizenship": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.RefreshRequest": {
            "type": "object",
            "required": [
                "refresh_token"
            ],
            "properties": {
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.RegisterRequest": {
            "type": "object",
            "required": [
                "email",
                "password"
            ],
            "properties": {
                "email": {
                    "type": "string"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8
                }
            }
        },
        "dto.RegisterResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "dto.RequiredFiles": {
            "type": "object",
            "properties": {
                "missing": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    },
                    "example": [
                        "selfie"
                    ]
                },
                "ok": {
                    "type": "boolean"
                }
            }
        },
        "dto.TokenPair": {
            "type": "object",
            "properties": {
                "access_expires_at": {
                    "type": "string"
                },
                "access_token": {
                    "type": "string"
                },
                "refresh_expires_at": {
                    "type": "string"
                },
                "refresh_token": {
                    "type": "string"
                }
            }
        },
        "dto.UpdateProfile": {
            "type": "object",
            "properties": {
                "birth_date": {
                    "type": "string"
                },
                "citizenship": {
                    "type": "string"
                },
                "first_name": {
                    "type": "string"
                },
                "last_name": {
                    "type": "string"
                },
                "phone": {
                    "type": "string"
                }
            }
        },
        "dto.UploadTicket": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "file_id": {
                    "type": "string"
                },
                "upload_url": {
                    "type": "string"
                }
            }
        },
        "dto.User": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                }
            }
        },
        "dto.ValidateTokenRequest": {
            "type": "object",
            "required": [
                "access_token"
            ],
            "properties": {
                "access_token": {
                    "type": "string"
                }
            }
        },
        "dto.ValidateTokenResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Access-токен из POST /auth/login в формате \"Bearer \u003ctoken\u003e\".",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    },
    "tags": [
        {
            "description": "Регистрация, вход, обновление и отзыв токенов",
            "name": "auth"
        },
        {
            "description": "Карточка клиента, профиль и статус",
            "name": "customer"
        },
        {
            "description": "Загрузка и выдача файлов клиента через presigned-ссылки",
            "name": "files"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "Banking Mini Cores API Gateway",
	Description:      "HTTP-фасад над gRPC-сервисами: аутентификация, работа с клиентами и их файлами.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
