server:
  host: localhost
  port: 50051

jwks:
  host: localhost
  port: 8081

database:
  host: localhost
  port: 5451
  user: banking_auth
  password: 123
  dbname: banking_auth
  ssl_mode: disable

admin:
  email: admin@banking.local
  password: "admin123"

jwt:
  private_key_path: ./configs/jwt_private_key.pem
  access_ttl: 15m
  refresh_ttl: 720h

request_timeout: 30s